spring.application.name=cohorte

db.url = jdbc:mysql://localhost:3306/cohorte?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username = root
db.password = root

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

secret.key = UNIDAD3BAMG